### ISSUE TITLE
For specific recipients

### ISSUE THREAD

**Issue by bencagri** [jsmrcaga/miniNotif#1]
Hi there, thx for this beautiful repo.

I wonder is it possible to send notifications to recipients . 
Here is an example;
There are two user types.
- Authors
- Editors.

When author writes an entry, send notification to editors .
If one of editor approve entry, send notification to author. (Not all of the authors)
Is it possible to use tag for this?
Thx.

**Comment by jsmrcaga** [comment]
Hey there! I see what you mean. 
As you can see miniNotif only works int client-side javascript, and generates a notification from your browser's API. So you can't really ask it to differenciate users (unless you do it yourself while the user is visiting the page).

However, if you want to send push notifications (which would enable you to send desktop notifications as well as android push notifications), I recommend you this article: [Push notifications on the open web](https://developers.google.com/web/updates/2015/03/push-notifications-on-the-open-web?hl=en). I'm building a library that uses it (already working) but I have to make a tutorial on how to use it. 

If you want to check it out it's right [here](http://workshop.jocolina.tk)! (Documentation not yet available, but in progress ;) )

**Comment by bencagri** [comment]
Thx for the information @jsmrcaga 
 I've read the documents about Push Notifications. I also will checkout your workshop.js.
